import { NAME } from './constants';
export default {
  SET_IS_RESIZING: `${NAME}/SET_IS_RESIZING`,
  SET_NEW_POSITION: `${NAME}/SET_NEW_POSITION`,
  SET_START_POSITION: `${NAME}/SET_START_POSITION`,
};
