import { NAME } from './constants';

export const PAUSE = `${NAME}/PAUSE`;
export const PLAY = `${NAME}/PLAY`;
export const SEQUENCE_STEP = `${NAME}/SEQUENCE_STEP`;
export const SET_ACTIVE_SYNTHS = `${NAME}/SET_ACTIVE_SYNTHS`;
export const SET_MEASURE_COUNT = `${NAME}/SET_MEASURE_COUNT`;
export const SET_POSITION = `${NAME}/SET_POSITION`;
export const SET_SEQUENCES = `${NAME}/SET_SEQUENCES`;
export const SET_SONG_POSITION = `${NAME}/SET_SONG_POSITION`;
export const SET_SONG_SEQUENCE = `${NAME}/SET_SONG_SEQUENCE`;
export const START_POINT_SET = `${NAME}/START_POINT_SET`;
export const SET_SYNTHS = `${NAME}/SET_SYNTHS`;
export const SET_TRANSPORT_POSITION = `${NAME}/SET_TRANSPORT_POSITION`;
export const SONG_SEQUENCE_STEP = `${NAME}/SONG_SEQUENCE_STEP`;
export const STOPPED = `${NAME}/STOPPED`;
export const TOGGLE_PLAY_PAUSE = `${NAME}/TOGGLE_PLAY_PAUSE`;
export const UPDATE_SEQUENCES = `${NAME}/UPDATE_SEQUENCES`;
