import { NAME } from './constants';

export const PLAYBACK_PAUSED = `${NAME}/PAUSE`;
export const PLAYBACK_STARTED = `${NAME}/PLAYBACK_STARTED`;
export const PLAYBACK_STOPPED = `${NAME}/PLAYBACK_STOPPED`;
export const PLAYBACK_TOGGLED = `${NAME}/PLAYBACK_TOGGLED`;
export const POSITION_SET = `${NAME}/POSITION_SET`;
export const SEQUENCE_STEP_TRIGGERED = `${NAME}/SEQUENCE_STEP_TRIGGERED`;
export const SEQUENCES_SET = `${NAME}/SEQUENCES_SET`;
export const SEQUENCES_UPDATED = `${NAME}/SEQUENCES_UPDATED`;
export const SONG_POSITION_SET = `${NAME}/SONG_POSITION_SET`;
export const SONG_SEQUENCE_SET = `${NAME}/SONG_SEQUENCE_SET`;
export const SONG_SEQUENCE_STEP_TRIGGERED = `${NAME}/SONG_SEQUENCE_STEP`;
export const START_POINT_SET = `${NAME}/START_POINT_SET`;
export const TRANSPORT_POSITION_SET = `${NAME}/TRANSPORT_POSITION_SET`;
