import { NAME } from './constants';

export const MOUSE_MOVED = `${NAME}/MOUSE_MOVED`;
export const SCROLLED_HORIZONTALLY = `${NAME}/SCROLLED_HORIZONTALLY`;
export const SCROLLED_VERTICALLY = `${NAME}/SCROLLED_VERTICALLY`;
export const SET_MOUSE_POINT = `${NAME}/SET_MOUSE_POINT`;
export const SET_SCROLL_LEFT = `${NAME}/SET_SCROLL_LEFT`;
export const SET_SCROLL_TOP = `${NAME}/SET_SCROLL_TOP`;
export const SET_TOOL_TYPE = `${NAME}/SET_TOOL_TYPE`;
export const SELECT_TOOL = `${NAME}/SELECT_TOOL`;
