import { NAME } from './constants';

export const APPLY_STAGED_TRACK = `${NAME}/APPLY_STAGED_TRACK`;
export const CLEAR_STAGED_TRACK = `${NAME}/CLEAR_STAGED_TRACK`;
export const DELETE_STAGED_TRACK = `${NAME}/DELETE_STAGED_TRACK`;
export const DESELECT_SEQUENCE = `${NAME}/DESELECT_SEQUENCE`;
export const SELECT_SEQUENCE = `${NAME}/SELECT_SEQUENCE`;
export const STAGE_TRACK = `${NAME}/STAGE_TRACK`;
export const UPDATE_STAGED_SYNTH_TYPE = `${NAME}/UPDATE_STAGED_SYNTH_TYPE`;
