/* eslint-disable */
export default {
  'arrow-down': require('react-icons/lib/fa/arrow-down'),
  'arrow-left': require('react-icons/lib/fa/arrow-left'),
  'arrow-right': require('react-icons/lib/fa/arrow-right'),
  'arrow-up': require('react-icons/lib/fa/arrow-up'),
  'caret-down': require('react-icons/lib/fa/caret-down'),
  'chevron-left': require('react-icons/lib/fa/chevron-left'),
  'chevron-right': require('react-icons/lib/fa/chevron-right'),
  cog: require('react-icons/lib/fa/cog'),
  clone: require('react-icons/lib/fa/clone'),
  close: require('react-icons/lib/fa/close'),
  eraser: require('react-icons/lib/fa/eraser'),
  'hand-paper-o': require('react-icons/lib/fa/hand-paper-o'),
  'long-arrow-down': require('react-icons/lib/fa/long-arrow-down'),
  'long-arrow-left': require('react-icons/lib/fa/long-arrow-left'),
  'long-arrow-right': require('react-icons/lib/fa/long-arrow-right'),
  'long-arrow-up': require('react-icons/lib/fa/long-arrow-up'),
  'mouse-pointer': require('react-icons/lib/fa/mouse-pointer'),
  pause: require('react-icons/lib/fa/pause'),
  pencil: require('react-icons/lib/fa/pencil'),
  play: require('react-icons/lib/fa/play'),
  plus: require('react-icons/lib/fa/plus'),
  redo: require('react-icons/lib/fa/repeat'),
  stop: require('react-icons/lib/fa/stop'),
  trash: require('react-icons/lib/fa/trash'),
  undo: require('react-icons/lib/fa/rotate-left'),
};
