import { NAME } from './constants';

export default {
  SET_MEASURE_COUNT: `${NAME}/SET_MEASURE_COUNT`,
  SET_MOUSE_POSITION: `${NAME}/SET_MOUSE_POSITION`,
  SET_SCROLL_LEFT: `${NAME}/SET_SCROLL_LEFT`,
  SET_SCROLL_TOP: `${NAME}/SET_SCROLL_TOP`,
  SET_SYNTH_TYPE: `${NAME}/SET_SYNTH_TYPE`,
  SET_TOOL_TYPE: `${NAME}/SET_TOOL_TYPE`,
};
