export default {
  SET_IS_PANNING: 'sequence/SET_IS_PANNING',
  SET_PAN_START_POSITION: 'sequence/SET_PAN_START_POSITION',
  SET_MEASURE_COUNT: 'sequence/SET_MEASURE_COUNT',
  SET_SYNTH_TYPE: 'sequence/SET_SYNTH_TYPE',
  SET_TOOL_TYPE: 'sequence/SET_TOOL_TYPE',
};
