export default {
  DELETE_NOTES: 'DELETE_NOTES',
  DRAW_NOTE: 'DRAW_NOTE',
  ERASE_NOTE: 'ERASE_NOTE',
  MOVE_NOTES: 'MOVE_NOTES',
  SELECT_NOTES: 'SELECT_NOTES',
  SET_MEASURE_COUNT: 'SET_MEASURE_COUNT',
  SET_POSITION: 'SET_POSITION',
  SET_SYNTH: 'SET_SYNTH',
  SET_TOOL: 'SET_TOOL',
};
