import { NAME } from './constants';

export const ADD_NOTES = `${NAME}/ADD_NOTES`;
export const ADD_SEQUENCES = `${NAME}/ADD_SEQUENCES`;
export const ADD_TRACKS = `${NAME}/ADD_TRACKS`;
export const CLOSE_SEQUENCE = `${NAME}/CLOSE_SEQUENCE`;
export const DELETE_NOTES = `${NAME}/DELETE_NOTES`;
export const DELETE_SEQUENCES = `${NAME}/DELETE_SEQUENCES`;
export const DELETE_TRACKS = `${NAME}/DELETE_TRACKS`;
export const DUPLICATE_NOTES = `${NAME}/DUPLICATE_NOTES`;
export const OPEN_SEQUENCE = `${NAME}/OPEN_SEQUENCE`;
export const SET_BPM = `${NAME}/SET_BPM`;
export const SET_NOTES = `${NAME}/SET_NOTES`;
export const SET_SEQUENCES = `${NAME}/SET_SEQUENCES`;
export const SET_SONG = `${NAME}/SET_SONG`;
export const SET_TRACKS = `${NAME}/SET_TRACKS`;
export const UPDATE_NOTES = `${NAME}/UPDATE_NOTES`;
export const UPDATE_SEQUENCES = `${NAME}/UPDATE_SEQUENCES`;
export const UPDATE_TRACK = `${NAME}/UPDATE_TRACK`;
export const UPDATE_TRACKS = `${NAME}/UPDATE_TRACKS`;
