import 'babel-polyfill';
import 'classnames';
import 'lodash';
import 'mousetrap';
import 'node-uuid';
import 'react';
import 'react-dom';
import 'react-hyperscript';
// import 'react-icons';
import 'react-redux';
import 'recompose';
import 'redux';
import 'redux-logger';
import 'redux-saga';
import 'tone';
