import { NAME } from './constants';

export const DESELECT_ALL = `${NAME}/DESELECT_ALL`;
export const DRAW = `${NAME}/DRAW`;
export const DUPLICATE = `${NAME}/DUPLICATE`;
export const ERASE = `${NAME}/ERASE`;
export const MOVE = `${NAME}/MOVE`;
export const MOVE_SELECTED = `${NAME}/MOVE_SELECTED`;
export const NUDGE_SELECTED_NOTES_POSITION = `${NAME}/NUDGE_SELECTED_NOTES_POSITION`;
export const NUDGE_SELECTED_NOTES_SIZE = `${NAME}/NUDGE_SELECTED_NOTES_SIZE`;
export const PUSH_REDO = `${NAME}/PUSH_REDO`;
export const PUSH_UNDO = `${NAME}/PUSH_UNDO`;
export const REDO = `${NAME}/REDO`;
export const REMOVE = `${NAME}/REMOVE`;
export const REMOVE_SELECTED = `${NAME}/REMOVE_SELECTED`;
export const RESIZE = `${NAME}/RESIZE`;
export const RESIZE_SELECTED = `${NAME}/RESIZE_SELECTED`;
export const SELECT_ALL = `${NAME}/SELECT_ALL`;
export const SELECT_NOTE = `${NAME}/SELECT_NOTE`;
export const SELECT_NOTES = `${NAME}/SELECT_NOTES`;
export const SET_REDOS = `${NAME}/SET_REDOS`;
export const SET_UNDOS = `${NAME}/SET_UNDOS`;
export const SHIFT_DOWN_OCTAVE = `${NAME}/SHIFT_DOWN_OCTAVE`;
export const SHIFT_UP_OCTAVE = `${NAME}/SHIFT_UP_OCTAVE`;
export const UNDO = `${NAME}/UNDO`;
