export default {
  SET_BPM: 'sound/SET_BPM',
  SET_MEASURE_COUNT: 'sound/SET_MEASURE_COUNT',
  SET_PLAYBACK_STATE: 'sound/SET_PLAYBACK_STATE',
  SET_POSITION: 'sound/SET_POSITION',
  SET_SYNTH: 'sound/SET_SYNTH',
};
