export default {
  DELETE_NOTES: 'notes/DELETE_NOTES',
  DRAW_NOTE: 'notes/DRAW_NOTE',
  ERASE_NOTE: 'notes/ERASE_NOTE',
  SELECT_NOTES: 'notes/SELECT_NOTES',
  SET_DRAG_EVENT: 'notes/SET_DRAG_EVENT',
  UPDATE_NOTE: 'notes/UPDATE_NOTE',
};
