import { NAME } from './constants';

export default {
  SET_NOTES: `${NAME}/SET_NOTES`,
  SET_NOTE_REDOS: `${NAME}/SET_NOTE_REDOS`,
  SET_NOTE_UNDOS: `${NAME}/SET_NOTE_UNDOS`,
  SET_SELECTED_NOTE_IDS: `${NAME}/SET_SELECTED_NOTE_IDS`,
};
