export default {
  DELETE_NOTE: 'notes/DELETE_NOTE',
  ADD_NOTES: 'notes/ADD_NOTES',
  ERASE_NOTE: 'notes/ERASE_NOTE',
  SELECT_NOTE: 'notes/SELECT_NOTE',
  SET_IS_DRAGGING: 'notes/SET_IS_DRAGGING',
  SET_DRAGGED_NOTE: 'notes/SET_DRAGGED_NOTE',
  SET_DRAG_OFFSET: 'notes/SET_DRAG_OFFSET',
  SET_DRAG_START_POSITION: 'notes/SET_DRAG_START_POSITION',
  UPDATE_NOTE: 'notes/UPDATE_NOTE',
};
